services:
  review-manager:
    image: ghcr.io/jo3qma/ocr-mng:latest
    ports:
      - "8088:8080"
    environment:
      RM_ADMIN_PASSWORD: ${RM_ADMIN_PASSWORD:-}
      RM_ADMIN_USER: ${RM_ADMIN_USER:-}
      RM_ENCRYPTION_KEY: ${RM_ENCRYPTION_KEY:-}
    volumes:
      - rm-data:/data
    restart: unless-stopped

volumes:
  rm-data:
